name: Find new scholarships

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *" # Every 12 hours

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3

      - name: setup python with pip cache
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"

      - name: upgrade pip
        run: pip install --upgrade pip

      - name: install any new dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        env:
          EMAIL_PASSCODE: ${{ secrets.EMAIL_PASSCODE }}
          SENDER_EMAIL_ADDRESS: ${{ secrets.SENDER_EMAIL_ADDRESS }}
        run: pytest
  find-scholarships:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3

      # https://github.com/actions/setup-python#caching-packages-dependencies
      - name: setup python with pip cache
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip" # caching pip dependencies

      - name: upgrade pip
        run: pip install --upgrade pip

      - name: install any new dependencies
        run: pip install -r requirements.txt

      - name: execute py script
        env:
          EMAIL_PASSCODE: ${{ secrets.EMAIL_PASSCODE }}
          SENDER_EMAIL_ADDRESS: ${{ secrets.SENDER_EMAIL_ADDRESS }}
        run: python src/main.py # execute main.py from src folder

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          timestamp=$(date -u)
          git diff-index --quiet HEAD || (git commit -a -m "Last update : ${timestamp}" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
  deploy-atom-feed:
    needs: [run-tests, find-scholarships]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend
